:doctype: book
:imagesdir: ./images
:iconsdir: ./icons
:nofooter:
:hide-uri-scheme: 

- Julian +
**location:** OR

[#Resume]
=== Resume
- **Last built:** {build_time} **UTC**

ifndef::backend-pdf[]
[pass]
++++
<a href="https://cv.sine.zip/cv.pdf">Download as pdf</a>
++++
endif::[]

=== Contact

=== Contact

- link:https://www.linkedin.com/in/running-toast[LinkedIn]
- link:https://github.com/Icey-Glitch[GitHub]
- mailto:jalex@riseup.net[Email]

=== IT Skills
**Core Skills:** ::

- **System Administration:**  practical experience with enterprise networking concepts at a small scale +
    and cloud deployment using Cloudflare.
- **Tooling:** Proficient with Nix, K8S, Proxmox, actively learning and contributing.
- **Software Development:** Proficient in C#, GO, Lua, Python, C++, C99, Rust, NodeJS.
- **Networking:** Experience with Home/Small office networking, +
    S2S vpns, On Site hosting, and Packet-Tracer.
- **Security:** Familiar with windows memory forensics, malware analysis + 
and identification, as well as implementing network security policies.

**Operating Systems:**

- Linux: Rocky Linux, Debian Bullseye, Nix
- Microsoft Windows: Windows 7-11

---
=== General Skills
**Software:** ::
- **Google sheets:**
** XML data import and other advanced functions.
- **Powerpoint**
- **Word**
- **Excel:**
** VB scripting

---
=== Personal Projects & Experience 


**System Administration & Security:** ::

  - IB: Middle Years Program, project focusing on learning comptia Net+ equivelent skills along with zero trust architecture.
  - Conducting isolated network trials of malware samples to develop malware prevention procedures.
  ** Aswell as documenting for reproduction and steps taken before and after to gather data.
  
**Tooling:** ::

  - Actively involved in community projects around a infrastructure as code tool called nix
  - managing personal nix configurations on GitHub. https://github.com/Icey-Glitch/NixDots
  - Syncplay protocol reimp in go https://github.com/Icey-Glitch/syncplay-G
  - Contributed to some open-source projects. +
  **GitHub PRs:**
  ** https://github.com/fufexan/dotfiles/pull/34[FufexanDotfiles]
  ** https://github.com/ScoopInstaller/Extras/pull/12758[ScoopInstaller]
  ** https://github.com/Alxs009/Universal-Math-Fixer/pull/2[Universal-Math-Fixer]
  - This site https://github.com/Icey-Glitch/Man-CV/ !!!

ifndef::backend-pdf[]
[pass]  
++++
<img src="https://github.com/Icey-Glitch/Man-CV/actions/workflows/main.yml/badge.svg" alt="Italian Trulli">
++++
endif::[]
  
**Software Development:** ::

  - Contributed to a closed-source game modding project for Unity games using a C# to native compiler called IL2cpp.
  - Developed and maintain personal websites along with building tools to automate tasks + 
  pulling data from noaa using rust and logging in a json. Developing 3rd party addons to games for me and friends.
  
**Networking:** ::

  - Managing a home network with Opnsense and Tailscale + malware lab and other services.
  - Practiced network troubleshooting using Packet-Tracer.
  
**Security:** ::

  - Conducted research on memory forensics and malware detection techniques.
  - Implemented fail2ban and IDS systems to secure sensitive endpoints.
  
---

=== Academic Record
**EHCS (2024-25):** ::
- Starting winter term 25
- PCC 162 (c++ year 2)

**High School (2024-25):** ::
- Pcc 161B dual credit (c++ year 1)

**High School (2023-24):** ::
- Java Programming dual credit.
- Active involvement in Game Dev Club and George Fox CS Competition.

=== Language Skills

**Fluent:** English

**Learning:** Spanish

=== Personal Interests

- Rock Climbing
- Biking
- Orwell's 1984 and Alien

---

ifndef::backend-pdf[]
[pass]  
++++
<center>
  <p>This site is freely available under the <strong>BSD-3</strong> clause <a href="https://github.com/Icey-Glitch/Man-CV/">[Source]</a>.</p>
</center>
++++
endif::[]
