:doctype: book
:imagesdir: ./images
:iconsdir: ./icons
:nofooter:

- Julian +
**location:** OR

[#Resume]
=== Resume
- **Last built:** {build_time} **UTC**

ifndef::backend-pdf[]
[pass]
++++
<a href="https://cv.sine.zip/cv.pdf">Download as pdf</a>
++++
endif::[]

=== IT Skills
**Core Skills:** ::

- **System Administration:**  practical experience with enterprise networking concepts at a small scale +
    and cloud deployment using Cloudflare.
- **Tooling:** Proficient with Nix, K8S, Proxmox, actively learning and contributing.
- **Software Development:** Proficient in C#, Lua, Python, C++, C99, Rust, NodeJS.
- **Networking:** Experience with Home/Small office networking, +
    S2S vpns, On Site hosting, and Packet-Tracer.
- **Security:** Familiar with windows memory forensics, malware analysis + 
and identification, as well as implementing network security policies.

**Operating Systems:**

- Linux: Rocky Linux, Debian Bullseye, Nix
- Microsoft Windows: Windows 7-11

---
=== Personal Projects & Experience 


**System Administration & Security:** ::

  - IB: Middle Years Program, project focusing on learning comptia Net+ equivelent skills along with zero trust architecture.
  - Conducting isolated network trials of malware samples to develop malware prevention procedures.
  ** Aswell as documenting for reproduction and steps taken before and after to gather data.
  
**Tooling:** ::

  - Actively involved in community projects around a infrastructure as code tool called nix
  - managing personal nix configurations on GitHub. https://github.com/Icey-Glitch/NixDots
  - Contributed to some open-source projects.
  ** https://github.com/fufexan/dotfiles/pull/34
  ** https://github.com/ScoopInstaller/Extras/pull/12758
  ** https://github.com/Alxs009/Universal-Math-Fixer/pull/2
  - this site https://github.com/Icey-Glitch/Man-CV/ !!!

ifndef::backend-pdf[]
[pass]  
++++
<img src="https://github.com/Icey-Glitch/Man-CV/actions/workflows/main.yml/badge.svg" alt="Italian Trulli">
++++
endif::[]
  
**Software Development:** ::

  - Contributed to a closed-source game modding project for Unity games using a C# to native compiler called IL2cpp.
  - Developed and maintain personal websites along with building tools to automate tasks + 
  pulling data from noaa using rust and logging in a json. Developing 3rd party addons to games for me and friends.
  
**Networking:** ::

  - Managing a home network with Opnsense and Tailscale + malware lab and other services.
  - Practiced network troubleshooting using Packet-Tracer.
  
**Security:** ::

  - Conducted research on memory forensics and malware detection techniques.
  - Implemented fail2ban and IDS systems to secure sensitive endpoints.
  
---

=== Academic Record


**Primary & Middle School:** ::
- Various achievements including participation in robotics and stock market game.

**High School (2023-24):** ::
- Java Programming dual credit.
- Active involvement in Game Dev Club and George Fox CS Competition.
- Forecasted completion of Systems Design in C++ dual credit.

=== Language Skills

**Fluent:** English

**Learning:** Spanish

=== Personal Interests

- Rock Climbing
- Biking
- Orwell's 1984 and Alien


