on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build site
        run: nix build .#pages --print-build-logs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: ./result

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages
          path: ./result
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 3597eb148572990301de37d103c9b11a
          projectName: coverletter
          directory: ./result
          branch: main
          wranglerVersion: "3"
          logsOnFailure: false
