on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix_version: [ '2.3.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          upstream-cache: https://cache.nixos.org
          nix_conf: experimental-features = nix-command flakes
          nix_version: ${{ matrix.nix_version }}
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: check
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build site
        run: nix build .#pages --print-build-logs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: ./result

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages
          path: ./result

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 3597eb148572990301de37d103c9b11a
          projectName: coverletter
          directory: ./result
          branch: main
          wranglerVersion: '3'
          logsOnFailure: false
